import type { Imovel } from './tipos';

/**
 * Imóveis INVENTADOS, só para desenhar as páginas no `next dev` enquanto o
 * banco não existe. `dados.ts` garante que eles nunca saem em build de produção.
 * O "[EXEMPLO]" no título é para ninguém confundir numa captura de tela.
 */
export const IMOVEIS_DE_EXEMPLO: Imovel[] = [
  {
    codigo: 'EX1',
    slug: 'exemplo-apartamento-2-quartos-meia-praia-itapema-ex1',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Apartamento 2 quartos em Meia Praia',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'apartamento',
    finalidades: ['aluguel'],
    status: 'disponivel',
    precoVendaCents: null,
    aluguelCents: 350_000,
    condominioCents: 60_000,
    iptuAnualCents: 120_000,
    quartos: 2,
    suites: 1,
    banheiros: 2,
    vagas: 1,
    areaM2: 72,
    areaTotalM2: null,
    bairro: 'Meia Praia',
    cidade: 'Itapema',
    fotos: [],
    comodidades: ['piscina', 'churrasqueira', 'elevador'],
    destaque: true,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
  },
  {
    codigo: 'EX2',
    slug: 'exemplo-kitnet-centro-itapema-ex2',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Kitnet mobiliada no Centro',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'kitnet',
    finalidades: ['aluguel'],
    status: 'disponivel',
    precoVendaCents: null,
    aluguelCents: 180_000,
    condominioCents: null,
    iptuAnualCents: null,
    quartos: 1,
    suites: null,
    banheiros: 1,
    vagas: null,
    areaM2: 30,
    areaTotalM2: null,
    bairro: 'Centro',
    cidade: 'Itapema',
    fotos: [],
    comodidades: ['mobiliado'],
    destaque: false,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
  },
  {
    codigo: 'EX3',
    slug: 'exemplo-casa-3-quartos-pereque-porto-belo-ex3',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Casa 3 quartos no Perequê',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'casa',
    finalidades: ['venda'],
    status: 'disponivel',
    precoVendaCents: 89_000_000,
    aluguelCents: null,
    condominioCents: null,
    iptuAnualCents: 250_000,
    quartos: 3,
    suites: 1,
    banheiros: 2,
    vagas: 2,
    areaM2: 140,
    areaTotalM2: null,
    bairro: 'Perequê',
    cidade: 'Porto Belo',
    fotos: [],
    comodidades: ['churrasqueira', 'aceita_pet'],
    destaque: true,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
  },
  {
    codigo: 'EX4',
    slug: 'exemplo-apartamento-3-quartos-meia-praia-itapema-ex4',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Apartamento 3 quartos, venda ou aluguel',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'apartamento',
    finalidades: ['venda', 'aluguel'],
    status: 'reservado',
    precoVendaCents: 145_000_000,
    aluguelCents: 520_000,
    condominioCents: 90_000,
    iptuAnualCents: 300_000,
    quartos: 3,
    suites: 3,
    banheiros: 4,
    vagas: 2,
    areaM2: 118,
    areaTotalM2: null,
    bairro: 'Meia Praia',
    cidade: 'Itapema',
    fotos: [],
    comodidades: ['piscina', 'academia', 'vista_mar'],
    destaque: false,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
  },
];
