import { mesCorrente } from '@juliana/contracts';

import type { Imovel } from './tipos';

/**
 * Imóveis INVENTADOS, só para desenhar as páginas no `next dev` enquanto o
 * banco não existe. `dados.ts` garante que eles nunca saem em build de produção.
 * O "[EXEMPLO]" no título é para ninguém confundir numa captura de tela.
 */
export const IMOVEIS_DE_EXEMPLO: Imovel[] = [
  {
    codigo: 'EX1',
    slug: 'exemplo-apartamento-2-quartos-meia-praia-itapema-ex1',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Apartamento 2 quartos em Meia Praia',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'apartamento',
    finalidades: ['aluguel'],
    status: 'disponivel',
    precoVendaCents: null,
    precoDeTabelaCents: null,
    aluguelCents: 350_000,
    condominioCents: 60_000,
    iptuAnualCents: 120_000,
    quartos: 2,
    suites: 1,
    banheiros: 2,
    vagas: 1,
    areaM2: 72,
    areaTotalM2: null,
    bairro: 'Meia Praia',
    cidade: 'Itapema',
    fotos: [],
    caracteristicas: {
      unidade: { itens: ['sacada', 'churrasqueira_carvao', 'piso_porcelanato'] },
      empreendimento: { itens: ['elevador', 'box_praia'] },
      lazer: { itens: ['piscina', 'salao_festas'] },
    },
    destaque: true,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
    empreendimento: null,
  },
  {
    codigo: 'EX2',
    slug: 'exemplo-kitnet-centro-itapema-ex2',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Kitnet mobiliada no Centro',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'kitnet',
    finalidades: ['aluguel'],
    status: 'disponivel',
    precoVendaCents: null,
    precoDeTabelaCents: null,
    aluguelCents: 180_000,
    condominioCents: null,
    iptuAnualCents: null,
    quartos: 1,
    suites: null,
    banheiros: 1,
    vagas: null,
    areaM2: 30,
    areaTotalM2: null,
    bairro: 'Centro',
    cidade: 'Itapema',
    fotos: [],
    caracteristicas: { unidade: { itens: ['mobiliado'] } },
    destaque: false,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
    empreendimento: null,
  },
  {
    codigo: 'EX3',
    slug: 'exemplo-casa-3-quartos-pereque-porto-belo-ex3',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Casa 3 quartos no Perequê',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'casa',
    finalidades: ['venda'],
    status: 'disponivel',
    precoVendaCents: 89_000_000,
    precoDeTabelaCents: 95_000_000,
    aluguelCents: null,
    condominioCents: null,
    iptuAnualCents: 250_000,
    quartos: 3,
    suites: 1,
    banheiros: 2,
    vagas: 2,
    areaM2: 140,
    areaTotalM2: null,
    bairro: 'Perequê',
    cidade: 'Porto Belo',
    fotos: [],
    caracteristicas: {
      unidade: { itens: ['quintal', 'espaco_gourmet', 'churrasqueira_carvao', 'aceita_pet'], outros: ['Poço artesiano'] },
      adicionais: { outros: ['Escriturado'] },
    },
    destaque: true,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
    empreendimento: null,
  },
  {
    codigo: 'EX4',
    slug: 'exemplo-apartamento-3-quartos-meia-praia-itapema-ex4',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Apartamento 3 quartos, venda ou aluguel',
    descricao:
      'Imóvel de exemplo para desenvolvimento do site. Texto, valores e características são fictícios.',
    tipo: 'apartamento',
    finalidades: ['venda', 'aluguel'],
    status: 'reservado',
    precoVendaCents: 145_000_000,
    precoDeTabelaCents: null,
    aluguelCents: 520_000,
    condominioCents: 90_000,
    iptuAnualCents: 300_000,
    quartos: 3,
    suites: 3,
    banheiros: 4,
    vagas: 2,
    areaM2: 118,
    areaTotalM2: null,
    bairro: 'Meia Praia',
    cidade: 'Itapema',
    fotos: [],
    caracteristicas: {
      unidade: { itens: ['vista_mar', 'varanda_gourmet', 'suite_master'] },
      empreendimento: { itens: ['portaria_24h', 'elevador', 'box_praia'] },
      lazer: { itens: ['piscina', 'academia', 'salao_jogos'] },
    },
    destaque: false,
    atualizadoEm: '2026-09-24T12:00:00.000Z',
    empreendimento: null,
  },
  {
    // Empreendimento com unidades: o "a partir de" é a mais barata disponível
    // (o 804), e o 1702 reservado aparece só com o selo: chega sem preço, como
    // o banco o manda, e fica fora da busca por preço.
    codigo: 'EX5',
    slug: 'exemplo-apartamentos-na-planta-morretes-itapema-ex5',
    slugsAntigos: [],
    titulo: '[EXEMPLO] Apartamentos na planta em Morretes',
    descricao:
      'Empreendimento de exemplo para desenvolvimento do site. Texto, valores, unidades e registro são fictícios.',
    tipo: 'apartamento',
    finalidades: ['venda'],
    status: 'disponivel',
    precoVendaCents: 84_056_940,
    precoDeTabelaCents: null,
    aluguelCents: null,
    condominioCents: null,
    iptuAnualCents: null,
    quartos: null,
    suites: null,
    banheiros: null,
    vagas: null,
    areaM2: null,
    areaTotalM2: null,
    bairro: 'Morretes',
    cidade: 'Itapema',
    fotos: [],
    caracteristicas: {
      empreendimento: { itens: ['portaria_24h', 'elevador'] },
      lazer: { itens: ['piscina', 'academia', 'salao_festas'] },
    },
    destaque: true,
    atualizadoEm: '2026-10-08T12:00:00.000Z',
    empreendimento: {
      // A tabela "deste mês", para o `next dev` mostrar os preços em qualquer data.
      tabelaDoMes: mesCorrente(),
      tabelaVigente: true,
      unidadesDisponiveis: 4,
      obra: 'lancamento',
      anoDeEntrega: 2030,
      registroDeIncorporacao: 'R-0 00.000',
      cartorio: 'Registro de Imóveis de exemplo',
      condicaoDePagamento: '10% de entrada + 100 mensais + 7 anuais',
      plantas: [
        {
          nome: '2 suítes + lavabo',
          quartos: 0,
          suites: 2,
          banheiros: 3,
          vagas: 1,
          areaM2: 70,
          unidades: [
            { rotulo: '804', andar: 8, areaM2: 70, precoCents: 84_056_940, situacao: 'disponivel' },
            { rotulo: '1204', andar: 12, areaM2: 70, precoCents: 89_132_076, situacao: 'disponivel' },
            { rotulo: '1702', andar: 17, areaM2: 70, precoCents: null, situacao: 'reservado' },
          ],
        },
        {
          nome: '3 dormitórios',
          quartos: 2,
          suites: 1,
          banheiros: 2,
          vagas: 1,
          areaM2: 70,
          unidades: [
            { rotulo: '506', andar: 5, areaM2: 70, precoCents: 85_008_528, situacao: 'disponivel' },
            { rotulo: '701', andar: 7, areaM2: 70, precoCents: 88_497_684, situacao: 'disponivel' },
          ],
        },
      ],
    },
  },
];
